### ISSUE TITLE
No longer working with Java 15

### ISSUE THREAD

**Issue by TerDale** [gerib/userscripts#1]
Hi,
Nice script, thanks! Unfortunately, while it's properly working with javadoc for Java 11 & 13, with Java 15 the tree view is desperately empty.
Any clue?
Thanks in advance

**Comment by gerib** [comment]
Hi,

Thanks, too! The version at the time of developing JANITOR was 13. They changed, for instance, the URI path and the DOM with prior versions already. The script handled this up to v13. It works with v14 here, too.

No clue at the moment. I'm going to have a look at the v15 DOM if I can free some time.

Anyway, thanks for the info! I expected that they will change something in the future...again. And I was hoping that someone tells me about this then. :)

Cheers
Geri

**Comment by TerDale** [comment]
Ok, thanks in advance.

**Comment by gerib** [comment]
I updated JANITOR to work with Java 15's API doc.

There are still two minor display issues (mentioned in the TODO) but the basic functionality works here.

**Comment by TerDale** [comment]
Hey, great! I'll look into it...
Thanks!

**Comment by gerib** [comment]
https://github.com/gerib/userscripts/commit/d17636625214b6e64e7dff771af5568b9d86898d
