### ISSUE TITLE
Not working with Java 17

### ISSUE THREAD

**Issue by GHYNG** [gerib/userscripts#3]
The navigation box on the left is blank empty with only the visible title "JANITOR – Java API Navigation Is The Only Rescue". 

It works with the doc pages of Java 16 but not the ones of 17.

Javadoc page: https://docs.oracle.com/en/java/javase/17/docs/api/index.html

**Comment by gmurray13** [comment]
@gerib , I have a fix for this that I'd like to submit via a PR.  If this is OK with you, what's the best way to get this integrated into the main branch of the main repo?  I've committed my change to a branch in my fork of this repository: https://github.com/gmurray13/userscripts/tree/jdk-17-support.  Vielen Dank!

**Comment by gmurray13** [comment]
This is the first time I've created a commit on a fork in github.com, and it looks like it allowed me to create a PR in the main repository, which I've done.

**Comment by GHYNG** [comment]
@gmurray13 Your code works for me. Thank you very much. Its very helpful.

**Comment by gerib** [comment]
@gmurray13 Thanks for your adaptations! I merged them into the repo here.
